#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Oct 12 19:37:29 2019

@author: lw
"""

import sys,time

for i in range(20):
    sys.stdout.write('$')      #stdout是标准输出的意思，在一般电脑上，stdout的标准输出指的是计算机屏幕。
    sys.stdout.flush()
    time.sleep(0.1)